version: '3.9'
services:
  blog-readme.account.mongo:
    image: mongo:4.4
    restart: always
    container_name: blog-readme.account.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: blog-readme-account

    ports:
      - 27017:27017

    volumes:
      - blog-readme.account.mongo:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/blog-readme-account --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  blog-readme.account.mongo.ui:
    image: mongo-express
    restart: always
    container_name: readme.account.mongo.ui
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL:
        mongodb://admin:test@blog-readme.account.mongo:27017/

volumes:
  blog-readme.account.mongo:
